/**
 * Canonical paths for placeholder icons under /public/icons (Phase: design system).
 * Do not rename URLs without updating assets — see `scripts/generate-mca-placeholder-icons.mjs`.
 */
export const McaIcons = {
  ui: {
    check: "/icons/ui/check.svg",
    close: "/icons/ui/close.svg",
    plus: "/icons/ui/plus.svg",
    minus: "/icons/ui/minus.svg",
    warning: "/icons/ui/warning.svg",
    trash: "/icons/ui/trash.svg",
    drag: "/icons/ui/drag.svg",
    chevronDown: "/icons/ui/chevron-down.svg",
    chevronUp: "/icons/ui/chevron-up.svg",
    chevronLeft: "/icons/ui/chevron-left.svg",
    chevronRight: "/icons/ui/chevron-right.svg",
    menu: "/icons/ui/menu.svg",
    search: "/icons/ui/search.svg",
    filter: "/icons/ui/filter.svg",
    sort: "/icons/ui/sort.svg",
    externalLink: "/icons/ui/external-link.svg",
    moreHorizontal: "/icons/ui/more-horizontal.svg",
    copy: "/icons/ui/copy.svg",
    edit: "/icons/ui/edit.svg",
    home: "/icons/ui/home.svg",
    community: "/icons/ui/community.svg",
    creator: "/icons/ui/creator.svg",
  },
  collection: {
    binder: "/icons/collection/binder.svg",
    deck: "/icons/collection/deck.svg",
    cards: "/icons/collection/cards.svg",
    catalog: "/icons/collection/catalog.svg",
    analytics: "/icons/collection/analytics.svg",
    inventory: "/icons/collection/inventory.svg",
    grid: "/icons/collection/grid.svg",
    list: "/icons/collection/list.svg",
    arrowLeft: "/icons/collection/arrow-left.svg",
    arrowRight: "/icons/collection/arrow-right.svg",
    slotEmpty: "/icons/collection/slot-empty.svg",
    zoneMain: "/icons/collection/zone-main.svg",
    zoneSideboard: "/icons/collection/zone-sideboard.svg",
    zoneCommander: "/icons/collection/zone-commander.svg",
    setSymbol: "/icons/collection/set-symbol.svg",
    rarity: {
      common: "/icons/collection/rarity/common.svg",
      uncommon: "/icons/collection/rarity/uncommon.svg",
      rare: "/icons/collection/rarity/rare.svg",
      ultra: "/icons/collection/rarity/ultra.svg",
      secret: "/icons/collection/rarity/secret.svg",
    },
  },
  trading: {
    trades: "/icons/trading/trades.svg",
    matching: "/icons/trading/matching.svg",
    marketplace: "/icons/trading/marketplace.svg",
    offer: "/icons/trading/offer.svg",
    handshake: "/icons/trading/handshake.svg",
  },
  scan: {
    camera: "/icons/scan/camera.svg",
    scanFrame: "/icons/scan/scan-frame.svg",
    iris: "/icons/scan/iris.svg",
  },
  activity: {
    bell: "/icons/activity/bell.svg",
    pulse: "/icons/activity/pulse.svg",
    history: "/icons/activity/history.svg",
    sparkles: "/icons/activity/sparkles.svg",
    timeline: "/icons/activity/timeline.svg",
    feed: "/icons/activity/feed.svg",
  },
  account: {
    user: "/icons/account/user.svg",
    achievements: "/icons/account/achievements.svg",
    billing: "/icons/account/billing.svg",
    signOut: "/icons/account/sign-out.svg",
    settings: "/icons/account/settings.svg",
    support: "/icons/account/support.svg",
  },
  system: {
    info: "/icons/system/info.svg",
    alert: "/icons/system/alert.svg",
    help: "/icons/system/help.svg",
    success: "/icons/system/success.svg",
    loading: "/icons/system/loading.svg",
    refresh: "/icons/system/refresh.svg",
  },
} as const;
